/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using System.Collections.Generic;
using UnityEngine;

namespace ExcelImporter.Editor.Templates.CompilingTemplates
{
    public abstract class AbstractSheetImport<T> : ScriptableObject
    {
        public List<T> Rows;

        protected AbstractSheetImport()
        {
            Rows = new List<T>();
        }
    }
}
