/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using System;

namespace ExcelImporter.Editor.Templates.CompilingTemplates
{
    public class SheetImport : AbstractSheetImport<SheetImport.Row>
    {
        [Serializable]
        public class Row
        {
            public int Id;
        }

        public SheetImport() : base() { }
    }
}
