/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using ExcelImporter.Editor.ExcelProcessing;
using ExcelImporter.Editor.Importers;
using ExcelImporter.Editor.Utility;
using ExcelImporter.Runtime.Imports;
using System.IO;
using UnityEditor;

namespace ExcelImporter.Editor.CodeTemplates.CompilingTemplates
{
    public class WorkbookImporter
    {
        private const string ExcelFilePath = "<EXCEL_FILEPATH>";
        private const string ImportBasePath = "<IMPORT_BASEPATH>";
        private const bool PrefixAssetName = true;

        [MenuItem("Tools/Excel Importer/Import WorkBookName", priority = 100)]
        public static void Import()
        {
            EditorUtils.Progress("Loading Workbook", 0f);
            var workbook = ExcelWorkbookFactory.Create(ExcelFilePath);

            //EditorUtils.Progress($"Importing Sheet: {sheetName}", 0.1f);
            //HandleSheet<SheetImport, SheetImport.Row>(workbook, sheetName);

            EditorUtils.Progress("Saving Assets", 1f);
            AssetDatabase.SaveAssets();

            UnityEngine.Debug.Log($"Imported {workbook.Sheets.Count} sheets from {workbook.FilePath}");
            EditorUtils.ProgressClear();
        }

        private static void HandleSheet<TSheet, TRow>(ExcelWorkbook workbook, string sheetName)
            where TSheet : AbstractImport<TRow>
            where TRow : new()
        {
            var importFilename = GetImportFilePath(workbook, sheetName, ImportBasePath, PrefixAssetName);
            SheetImporter.ImportData<TSheet, TRow>(workbook, sheetName, importFilename);
        }

        private static string GetImportFilePath(ExcelWorkbook workbook, string sheetName, string importBasePath, bool prefixAssetName)
        {
            var prefix = prefixAssetName ? $"{workbook.Name}." : string.Empty;
            var filename = $"{prefix}{sheetName}";

            return Path.Combine(importBasePath, filename);
        }
    }
}
