/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using System;

namespace Game.Data
{
    public class Sheet1Import : AbstractSheetImport<Sheet1Import.Row>
    {
        [Serializable]
        public class Row
        {
            public int Id;
            public string Name;
            public bool IsActive;
            public float Value;
            public double Cost;
            public long LongValue;

        }

        public Sheet1Import() : base() { }
    }
}
